spring:
      mvc:
         view:
             prefix: /WEB-INF/jsp/
             suffix: .jsp
      datasource:
              url: jdbc:mysql://127.0.0.1:3306/how2java?characterEncoding=UTF-8&useSSL=true
              username: root
              password: 123456
              driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
       mapper-locations: classpath:com/how2java/springboot/mapper/*.xml
       type-aliases-package: com.how2java.springboot.pojo

#http://localhost:8080/hello